### PR TITLE
Fix syntax

### PR DESCRIPTION
**Pull request by mvidner**
Fixup of #192 "Hardening"

- [x] changes and version
- [x] catch this automatically via`perl -c`

### CODE REVIEW

**Comment by jreidinger** [comment]
looks also good for me.

**Comment by mvidner** [comment]
@lslezak I suggest that we merge this only after you add the `perl -wc`, to test that it really catches the bug.

**Comment by lslezak** [comment]
JFYI: The Perl syntax check has been added in https://github.com/yast/docker-yast-cpp/pull/23 (and https://github.com/yast/docker-yast-ruby/pull/32).

**Comment by lslezak** [comment]
The Perl syntax check now works at Travis, see the output log: https://travis-ci.org/yast/yast-users/builds/477217161#L1017. (I just had to add the `perl-X500-DN` package to the install list.)

**Pull request merged**
