### PR TITLE
Add some missing elements to AutoYaST schema

### PR DESCRIPTION
**Pull request by imobach**
Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for this module. I'm not updating the changes file nor the spec because this version 3.1.37.1 is not submitted to IBS yet (so this fix willl be included in that version).

### CODE REVIEW

**Comment by schubi2** [comment]
Please adapt changes and spec file.

**Comment by imobach** [comment]
@schubi2 Done. Thanks!

**Comment by imobach** [comment]
Anyway, do not merge this change yet as I'm doing some final checks.

**Comment by imobach** [comment]
@schubi2 Ok, this PR is finished and ready for review.

**Comment by gabi2** [comment]
Ok, LGTM for this fix.

**Comment by imobach** [comment]
@gabi2 Thanks!

**Pull request merged**
